import React from "react";
import Link from "next/Link";

import ScreenSaver from "../../../components/ScreenSaver";

// const namedColors = [
//   "aliceblue",
//   "antiquewhite",
//   "aqua",
//   "aquamarine",
//   "azure",
//   "beige",
//   "bisque",
//   "black",
//   "blanchedalmond",
//   "blue",
//   "blueviolet",
//   "brown",
//   "burlywood",
//   "cadetblue",
//   "chartreuse",
//   "chocolate",
//   "coral",
//   "cornflowerblue",
//   "cornsilk",
//   "crimson",
//   "cyan",
//   "darkblue",
//   "darkcyan",
//   "darkgoldenrod",
//   "darkgray",
//   "darkgreen",
//   "darkgrey",
//   "darkkhaki",
//   "darkmagenta",
//   "darkolivegreen",
//   "darkorange",
//   "darkorchid",
//   "darkred",
//   "darksalmon",
//   "darkseagreen",
//   "darkslateblue",
//   "darkslategray",
//   "darkslategrey",
//   "darkturquoise",
//   "darkviolet",
//   "deeppink",
//   "deepskyblue",
//   "dimgray",
//   "dimgrey",
//   "dodgerblue",
//   "firebrick",
//   "floralwhite",
//   "forestgreen",
//   "fuchsia",
//   "gainsboro",
//   "ghostwhite",
//   "gold",
//   "goldenrod",
//   "gray",
//   "grey",
//   "green",
//   "greenyellow",
//   "honeydew",
//   "hotpink",
//   "indianred",
//   "indigo",
//   "ivory",
//   "khaki",
//   "lavender",
//   "lavenderblush",
//   "lawngreen",
//   "lemonchiffon",
//   "lightblue",
//   "lightcoral",
//   "lightcyan",
//   "lightgoldenrodyellow",
//   "lightgray",
//   "lightgreen",
//   "lightgrey",
//   "lightpink",
//   "lightsalmon",
//   "lightseagreen",
//   "lightskyblue",
//   "lightslategray",
//   "lightslategrey",
//   "lightsteelblue",
//   "lightyellow",
//   "lime",
//   "limegreen",
//   "linen",
//   "magenta",
//   "maroon",
//   "mediumaquamarine",
//   "mediumblue",
//   "mediumorchid",
//   "mediumpurple",
//   "mediumseagreen",
//   "mediumslateblue",
//   "mediumspringgreen",
//   "mediumturquoise",
//   "mediumvioletred",
//   "midnightblue",
//   "mintcream",
//   "mistyrose",
//   "moccasin",
//   "navajowhite",
//   "navy",
//   "oldlace",
//   "olive",
//   "olivedrab",
//   "orange",
//   "orangered",
//   "orchid",
//   "palegoldenrod",
//   "palegreen",
//   "paleturquoise",
//   "palevioletred",
//   "papayawhip",
//   "peachpuff",
//   "peru",
//   "pink",
//   "plum",
//   "powderblue",
//   "purple",
//   "rebeccapurple",
//   "red",
//   "rosybrown",
//   "royalblue",
//   "saddlebrown",
//   "salmon",
//   "sandybrown",
//   "seagreen",
//   "seashell",
//   "sienna",
//   "silver",
//   "skyblue",
//   "slateblue",
//   "slategray",
//   "slategrey",
//   "snow",
//   "springgreen",
//   "steelblue",
//   "tan",
//   "teal",
//   "thistle",
//   "tomato",
//   "turquoise",
//   "violet",
//   "wheat",
//   "white",
//   "whitesmoke",
//   "yellow",
//   "yellowgreen",
// ];

const namedColors = {
  aliceblue: "Alice Blue",
  antiquewhite: "Antique White",
  aqua: "Aqua",
  aquamarine: "Aquamarine",
  azure: "Azure",
  beige: "Beige",
  bisque: "Bisque",
  black: "Black",
  blanchedalmond: "Blanched Almond",
  blue: "Blue",
  blueviolet: "Blue Violet",
  brown: "Brown",
  burlywood: "Burlywood",
  cadetblue: "Cadet Blue",
  chartreuse: "Chartreuse",
  chocolate: "Chocolate",
  coral: "Coral",
  cornflowerblue: "Cornflower Blue",
  cornsilk: "Cornsilk",
  crimson: "Crimson",
  cyan: "Cyan",
  darkblue: "Dark Blue",
  darkcyan: "Dark Cyan",
  darkgoldenrod: "Dark Goldenrod",
  darkgray: "Dark Gray",
  darkgreen: "Dark Green",
  darkgrey: "Dark Grey",
  darkkhaki: "Dark Khaki",
  darkmagenta: "Dark Magenta",
  darkolivegreen: "Dark Olive Green",
  darkorange: "Dark Orange",
  darkorchid: "Dark Orchid",
  darkred: "Dark Red",
  darksalmon: "Dark Salmon",
  darkseagreen: "Dark Sea Green",
  darkslateblue: "Dark Slate Blue",
  darkslategray: "Dark Slate Gray",
  darkslategrey: "Dark Slate Grey",
  darkturquoise: "Dark Turquoise",
  darkviolet: "Dark Violet",
  deeppink: "Deep Pink",
  deepskyblue: "Deep Sky Blue",
  dimgray: "Dim Gray",
  dimgrey: "Dim Grey",
  dodgerblue: "Dodger Blue",
  firebrick: "Firebrick",
  floralwhite: "Floral White",
  forestgreen: "Forest Green",
  fuchsia: "Fuchsia",
  gainsboro: "Gainsboro",
  ghostwhite: "Ghost White",
  gold: "Gold",
  goldenrod: "Goldenrod",
  gray: "Gray",
  grey: "Grey",
  green: "Green",
  greenyellow: "Green Yellow",
  honeydew: "Honeydew",
  hotpink: "Hot Pink",
  indianred: "Indian Red",
  indigo: "Indigo",
  ivory: "Ivory",
  khaki: "Khaki",
  lavender: "Lavender",
  lavenderblush: "Lavender Blush",
  lawngreen: "Lawn Green",
  lemonchiffon: "Lemon Chiffon",
  lightblue: "Light Blue",
  lightcoral: "Light Coral",
  lightcyan: "Light Cyan",
  lightgoldenrodyellow: "Light Goldenrod Yellow",
  lightgray: "Light Gray",
  lightgreen: "Light Green",
  lightgrey: "Light Grey",
  lightpink: "Light Pink",
  lightsalmon: "Light Salmon",
  lightseagreen: "Light Sea Green",
  lightskyblue: "Light Sky Blue",
  lightslategray: "Light Slate Gray",
  lightslategrey: "Light Slate Grey",
  lightsteelblue: "Light Steel Blue",
  lightyellow: "Light Yellow",
  lime: "Lime",
  limegreen: "Lime Green",
  linen: "Linen",
  magenta: "Magenta",
  maroon: "Maroon",
  mediumaquamarine: "Medium Aquamarine",
  mediumblue: "Medium Blue",
  mediumorchid: "Medium Orchid",
  mediumpurple: "Medium Purple",
  mediumseagreen: "Medium Sea Green",
  mediumslateblue: "Medium Slate Blue",
  mediumspringgreen: "Medium Spring Green",
  mediumturquoise: "Medium Turquoise",
  mediumvioletred: "Medium Violet Red",
  midnightblue: "Midnight Blue",
  mintcream: "Mint Cream",
  mistyrose: "Misty Rose",
  moccasin: "Moccasin",
  navajowhite: "Navajo White",
  navy: "Navy",
  oldlace: "Old Lace",
  olive: "Olive",
  olivedrab: "Olive Drab",
  orange: "Orange",
  orangered: "Orange Red",
  orchid: "Orchid",
  palegoldenrod: "Pale Goldenrod",
  palegreen: "Pale Green",
  paleturquoise: "Pale Turquoise",
  palevioletred: "Pale Violet Red",
  papayawhip: "Papaya Whip",
  peachpuff: "Peach Puff",
  peru: "Peru",
  pink: "Pink",
  plum: "Plum",
  powderblue: "Powder Blue",
  purple: "Purple",
  rebeccapurple: "Rebecca Purple",
  red: "Red",
  rosybrown: "Rosy Brown",
  royalblue: "Royal Blue",
  saddlebrown: "Saddle Brown",
  salmon: "Salmon",
  sandybrown: "Sandy Brown",
  seagreen: "Sea Green",
  seashell: "Seashell",
  sienna: "Sienna",
  silver: "Silver",
  skyblue: "Sky Blue",
  slateblue: "Slate Blue",
  slategray: "Slate Gray",
  slategrey: "Slate Grey",
  snow: "Snow",
  springgreen: "Spring Green",
  steelblue: "Steel Blue",
  tan: "Tan",
  teal: "Teal",
  thistle: "Thistle",
  tomato: "Tomato",
  turquoise: "Turquoise",
  violet: "Violet",
  wheat: "Wheat",
  white: "White",
  whitesmoke: "White Smoke",
  yellow: "Yellow",
  yellowgreen: "Yellow Green",
};

function ScreenSaverIndex() {
  const colors = genereateRandomColors(20);

  return (
    <main>
      <h1>Choose a Color</h1>
      <div
        style={{
          marginTop: "1em",
          display: "grid",
          gridTemplateColumns: "repeat(5, 1fr)",
          gap: "1em",
        }}
      >
        {colors.map(function (colorKey) {
          return (
            <div
              style={{
                backgroundColor: colorKey,
                // margin: "1em 0",
                padding: "1em",
                borderRadius: "5px",
              }}
            >
              <Link
                href={"/exercises/01-screensaver/" + colorKey}
                style={{
                  backgroundColor: "black",
                  padding: "1em",
                  borderRadius: "5px",
                }}
              >
                {namedColors[colorKey]}
              </Link>
            </div>
          );
        })}
      </div>
    </main>
  );

  function getRandomColor() {
    return Object.keys(namedColors)[
      Math.floor(Math.random() * Object.keys(namedColors).length)
    ];
  }

  function genereateRandomColors(amount = 6) {
    const colors = Array(amount);

    for (let i = 0; i < amount; i++) {
      colors[i] = getRandomColor();
    }

    return colors;
  }
}

export default ScreenSaverIndex;
